// saga actions 정의
export const sagaActions = {
  FETCH_TEMPLATE: 'TEMPLATE/FETCH_TEMPLATE',
  ADD_TEMPLATE: 'TEMPLATE/ADD_TEMPLATE',
  DELETE_TEMPLATE: 'TEMPLATE/DELETE_TEMPLATE',
  UPDATE_TEMPLATE: 'TEMPLATE/UPDATE_TEMPLATE'
};